---
title: "Juli 2020"
page-layout: full
date: 2020-07-06
---

\
Liebe Freund:Innen, Unterstützer:Innen und Interessierte,

es ist wieder soweit - der nächste Newsletter aus der Freiau99 hat seinen Weg in euer Mailpostfach gefunden.\
Wir sind inzwischen schon fast drei Monate stolze Bewohner:Innen der nun selbstverwalteten Freiau99. Und was sollen wir sagen - es fühlt sich eigentlich gar nicht so anders an.

An das Plenieren haben wir uns inzwischen schon so sehr gewöhnt, dass es nicht mehr wegzudenken ist - es ist aber auch insofern etwas entspannter geworden, als dass es meistens weniger zu besprechen gibt und nur noch zweiwöchentlich stattfindet.

Natürlich tragen wir jetzt alle mehr Verantwortung als zuvor: Ob es nun darum geht, eine:N Techniker:In zu rufen, weil das Heißwasser nicht läuft, die Direktkredite zu verwalten oder über die Infomail erreichbar zu sein - all das gehört zu unseren neuen Aufgaben, die mit dem selbstverwalteten Wohnen einhergehen.\
Um ihnen gerecht zu werden, haben wir uns in einem Sonderplenum zusammengesetzt, und verschiedene AGs gegründet, um die Aufgaben und Zuständigkeiten unter uns aufzuteilen:\
So gibt es nun eine Hausmeister:Innen-AG, eine Finanz-AG, eine Buchhaltungs-AG, eine Direktkreditverwaltungs-AG und eine Öffentlichkeitsarbeits-AG.

Gerade haben vor allem Steffi und Jannis, die zusammen unsere Buchhaltung-AG bilden, erfahren, wieviel Arbeitsaufwand das mitunter bedeuten kann:\
Drei Tage am Stück wurden sie von morgens bis spätnachmittags von Achim in die Kunst der Buchhaltung eingeführt - weitere Termine folgen!\
Wir anderen haben nur die Köpfe durch die Küchentür rauchen hören - und wenn wir kurz von Unmut ergriffen wurden, weil wir für unseren Kaffee am Vormittag extra in die obere Küche hochstapfen mussten, so waren wir doch insgeheim froh, dass wir uns nicht selbst in dieses Hexenwerk einarbeiten müssen - an dieser Stelle ein großes Shout-Out an Jannis, Steffi und Achim - dafür, dass ihr euch bereit erklärt habt, diesen wichtigen Job zu übernehmen und dir Achim dafür, dass du die Zeit und Geduld aufbringst, den beiden dein Wissen weiterzuvermitteln!

Ansonsten hat der Frühling uns viel Zeit in unserem schönen Garten gebracht - ob Kaffee am Morgen, Lernen im Grün, Gärtnern oder in der Hängematte fläzen - wir genießen unseren Mini-Naturspot im sonst so lärmenden Straßendjungel!

\
Abschließend wollen wir euch noch erzählen, was uns Covid-19 gebracht hat. Und zwar an Positivem, denn Negatives hört mensch ja schon genug - hier also eine kleine Sammlung:

-   unzählige Doppelkopf-Abende (Für einen Teil von uns. Statistisch signifikanter Anstieg von 1/10 Bewohner:Innen, die die Spielregeln kennen auf 5/10!)

-   einen neuen Gartenzaun

-   abrasierte Augenbrauen

-   eine Testphase mit der App Solid zum Aufteilen von WG-Kosten, und die Entscheidung, sie wieder abzuschaffen

-   Koch-Experimente mit Tajine (Tajine auf dem Feuer, Tajine auf dem Ofen, süße Tajine, nicht süße Tajine, …)

![Die gestrichelte, vertikale Linie zeigt den Juli 2020 an. Da die Grafik 2025 erstellt wurde, entspricht der Fortlauf des Graphen der Realität. Wenn ihr den Code zu dieser wahnsinnig anspruchsvollen Grafik benötigt, fragt Mare, dieses Statistik-& -Programmier-Genie, was nicht nur die Grafik, sondern auch die gesamte Website programmiert hat.](Images/DKSpielerInnen.png)

Wir hoffen, euch mit diesem kleinen Einblick ein bisschen an den Entwicklungen unseres Projekts und unserem Zusammenleben teilhaben lassen zu können, und wünschen euch einen grandiosen Start in die Sommermonate!

Liebste Grüße,

eure Freiau99er:Innen!
