---
title: "Kreditverträge"
page-layout: full
toc: false
---

Direktkredite sind Nachrangdarlehen mit einer qualifizierten Rangrücktrittsklausel. Die Klausel besagt zum einen, dass kein Geld an die Direktkreditgebenden zurückgezahlt werden muss, falls damit die Zahlungsfähigkeit der Kreditnehmenden gefährdet ist. Zum anderen werden im Falle einer Insolvenz erst der Bankkredit und die Forderungen aller anderen nicht-nachrangigen Gläubiger:Innen bedient und dann erst die der Direktkreditgebenden.

Im Direktkreditvertrag sind folgende Punkte geregelt: Kreditbetrag, Verzinsung, Kündigungsfrist, Rangrücktrittsklausel, Anlagevolumen und Zweck.

## **Kreditbetrag**

Ihr könnt uns einen Kredit in Höhe von 500,- € oder mehr zur Verfügung stellen. Bei großen Beträgen gibt es auch die Möglichkeit, den Betrag in verschiedene Verträge zu diversen Zinssätzen aufzuteilen. Gerne beraten wir euch diesbezüglich persönlich. Schreibt uns einfach an!

## **Verzinsung**

Wir können keine hohen Zinsen zahlen, wenn wir den sozialen Charakter des Projekts erhalten wollen. Eine niedrige Zinsbelastung garantiert dauerhaft günstige Mietpreise und erlaubt uns, unsere Bankkredite schneller zu tilgen. Dementsprechend bieten wir Zinsen zwischen 0,1 und 1,5% an. Ihr könnt euch sicher sein, dass eine private Bereicherung durch Gewinne oder Spekulation unmöglich ist, da dies durch das besondere Modell des Mietshäuser Syndikats ausgeschlossen ist.

Ihr könnt euren Direktkredit unabhängig von Höhe und Kündigungsfrist entweder zinslos gewähren oder mit einem festen Zinssatz verbinden. Sofern ihr euch nicht anders äußert, werden die Zinsen am Ende des Jahres dem bereits angelegten Betrag zugeschlagen. Alternativ können die Zinsen auch ausbezahlt werden. Dies solltet Ihr gegebenenfalls in dem Kreditvertrag vermerken.

## **Kündigungsfrist**

Ihr könnt euer Geld mit einer Kündigungsfrist von sechs Monaten oder mehr bei uns anlegen. Kredite mit langen Kündigungsfristen sind für uns besonders hilfreich, weil sie eine hohe Planungssicherheit und niedrige Verwaltungskosten mit sich bringen. Gerade bei großen Kreditsummen ist dies wichtig. Zudem könnt Ihr mit uns einen Kredit bis zu einer festgelegten Vertragslaufzeit abschließen. Bei Fragen bezüglich der für euch am besten geeigneten Frist oder Laufzeit stehen wir Ihnen gerne zur Verfügung. Wir bitten euch, die vereinbarten Kündigungsfristen einzuhalten, damit wir sicher planen können. Ein fairer Umgang mit Geld ist uns wichtig, daher werden wir uns bemühen, die Rückzahlung des Geldes bei Bedarf auch vorzeitig zu ermöglichen.

## **Rangrücktrittsklausel**

Für den Fall eines ökonomischen Engpasses des Projekts können Direktkredite nicht sofort zurückgezahlt werden, wenn dadurch das Projekt zahlungsunfähig würde. Außerdem ist durch die Rangrücktrittsklausel festgelegt, dass im Insolvenzfall stets alle anderen Schuldner:Innen, insbesondere die Banken, zuerst ihr Geld zurück bekommen, bevor die Direktkreditgeber:Innen bedient werden. Den genauen Inhalt der Rangrücktrittsklausel findet Ihr im Direktkreditvertrag.

## **Zweck**

Die Direktkredite sind die Finanzierungsgrundlage für den Kauf des Hauses. Damit macht Ihr den derzeitigen Hausbewohner:Innen den Beibehalt ihrer Wohnsituation zu erschwinglichen Preisen möglich und unterstützen die Verwaltung des Gebäudes in Selbstorganisation.

## **Anlagevolumen**

Sowohl die Haus GmbH als auch der Freiau99 e.V. nehmen jeweils Direktkredite an. Im Rahmen des Vermögensanlagegesetzes geltet sie somit als die Ermittenden der Vermögensanlagen, die sich durch den Zinssatz unterscheiden. Im Rahmen jeder einzelnen Vermögensanlage werden maximal 20 Nachrangdarlehen oder innerhalb von 12 Monaten nicht mehr als ingesamt 100 000 Euro angenommen. Daher besteht keine Prospektpflicht nach dem Vermögensanlagegesetz.

Gerne informieren wir euch auch persönlich in einem Telefonat oder bei einem Treffen über die Risiken einer Kreditvergabe und besprechen Ihre Wünsche hinsichtlich Zinsen, Kündigungsfristen und Laufzeit. Kontaktiert uns über das Kontaktformular oder ruft einfach bei uns an.

## **Download**

Die Direktkreditvertragsvorlagen unterscheiden sich je nach geplantem Direktkreditbetrag:

-   Wenn ihr euch überlegt, einen Direktkredit von unter 7.000 € zu geben, so könnt Ihr [diesen Vertrag](https://cloud.syndikat.org/s/QL8jddyrCX4mpsA) nutzen.

-   Für Direktkredite ab einem Betrag von 7.000€ befindet sich der Vertrag [hier](https://cloud.syndikat.org/s/72zyTFcAzscJw2d).
