---
title: "Was sind Direktkredite"
page-layout: full
toc: false
---

Direktkredite sind Geldbeträge, die dem Projekt - ohne den Umweg über eine Bank - direkt geliehen werden. Sie bieten Einzelpersonen und Gruppierungen die Möglichkeit einer sinnvollen, sozialen, ökologischen und nachhaltigen Geldanlage. Dafür wird zwischen den Kreditgeber:Innen und dem Hausprojekt ein Kreditvertrag abgeschlossen. Diese Direktkredite sind Nachrangdarlehen mit einer qualifizierten Rangrücktrittsklausel. Die Klausel besagt zum einen, dass kein Geld an die Direktkreditgeber:Innen zurückgezahlt werden muss, falls damit die Zahlungsfähigkeit des Kreditnehmers (Freiau99 GmbH oder Freiau99 e.V.) gefährdet ist. Zum anderen werden im Falle einer Insolvenz erst der Bankkredit und dann erst die Direktkreditgeber:Innen bedient.

## **Warum Direktkredite?**

Banken stellen in der Regel nur einen Teil der Investitionskosten zur Verfügung. Sie setzen voraus, dass der andere Teil als Eigenkapital vorhanden ist. Wir als Mieter:Innen-Initiative haben jedoch kaum eigenes Kapital. Gerade deshalb sind wir ja auf bezahlbaren Wohnraum angewiesen! Der Ausweg besteht in einer Art Abkürzung: der Direktkredit. Ihr könnt Geld, das ihr nicht auf der Bank liegen lassen wollen, direkt bei unserer Haus-GmbH anlegen. Diese Direktkredite dienen dann als Ersatz-Eigenkapital für die Gewährung von Bankkrediten.

## **Was habt ihr davon?**

Was wir bieten können, ist die Gewissheit, dass euer Geld für einen sozialen Zweck statt für eine Bank “arbeitet”: Wir spekulieren nicht mit Wohnraum, sondern stellen ihn zu erschwinglichen Preisen zur Verfügung, wobei die Kredite langfristig über die Mieten abbezahlt werden. Gerne könnt ihr uns dann besuchen, um zu schauen, was bei uns gerade ansteht und inwiefern wir von euren Direktkrediten profitieren. Durch euch haben wir auch die Möglichkeit, dem Mietshäuser Syndikat den Solidarbeitrag auszurichten, der zur Unterstützung neu entstehender Projekte dient.

## **Zum Schluss für euch:**

Falls ihr Interesse habt, kontaktiert uns einfach! Über das Kontaktformular, telefonisch, oder per Post. Ihr bekommt dann den passenden Kreditvertrag je nach Wunsch per Post in zweifacher Ausführung oder per Mail zugesandt. Nach Erhalt des Vertrages füllt ihr diesen aus und sendet ihn an die GmbH zurück. Wir unterschreiben und schicken den Vertrag dann an euch zurück. Als letzten Schritt überweist ihr das Geld und schon sind wir im Geschäft!

Im Kreditvertrag wird geregelt:

-   Der Kreditbetrag (ab 500 Euro)

-   Zinsen

-   Kündigungsfrist (z.B. ab 6 Monate)
