---
title: "Wie finanzieren wir uns"
page-layout: full
toc: false
---

Die große Geldfrage!\
In unserem Fall teilt sich die Finanzierung in zwei:

1.  Einerseits haben wir einen Bankkredit aufgenommen. Dieser Kredit deckt jedoch nur ca. zwei Drittel des Kaufpreises und setzt zudem voraus, dass das restliche Drittel als Eigenkapital vorhanden ist.

2.  Aus diesem Grund sind wir auch auf Euch angewiesen! In Form von Direktkrediten (Nachrangdarlehen), könnt Ihr uns unterstützen. Direktkredite sind viele kleine (und auch größere) Beträge, die uns Unterstützende für einen festgelegten Zeitraum oder mit einer festgelegten Kündigungsfrist zu niedrigen Zinsen leihen. Dabei können Menschen, die das Projekt kennen und unterstützenswert finden, Ersparnisse direkt bei der Haus-GmbH anlegen. Dies passiert ohne Bank, die ihre Kosten und Gewinnspanne bezahlt haben will. Das macht den Bankkredit zwar nicht überflüssig, jedoch schließt eine ausreichende Zahl an zinsgünstigen Direktkrediten die Finanzierungslücke und hält die Mieten auf erträglichem Niveau.

Mehr über Direktkredite erfahrt ihr im Reiter “[Was sind Direktkredite?](https://freiau99.org/Was-sind-Direktkredite-.html)”.
