---
title: "Wie viel Sicherheit gibt es"
page-layout: full
toc: false
---

Richtig ist: Bankübliche Sicherheiten können wir nicht garantieren. Im Falle eines finanziellen Engpasses kann es unter Umständen dazu kommen, dass Direktkredite nicht sofort zurückgezahlt werden können, wenn andernfalls das Projekt zahlungsunfähig würde. In einem solchen Fall müsste vor der Rückzahlung zunächst eine alternative Finanzierung gefunden werden. Sollte es zum Extremfall einer Insolvenz kommen, erhalten zuerst andere Gläubiger, etwa Banken, ihr Geld zurück. Bei den circa 200 bestehenden Syndikats-Projekten ist bisher ein Projekt insolvent gegangen. Das heißt, dass es im schlimmsten Fall zu einem vollständigen Verlust des von Euch angelegten Geldes kommen könnte.

Wir sind uns bewusst, dass ein Projekt wie unseres mit vielen Risiken verbunden ist. Daher ist es wichtig, dass potenzielle Direktkreditgeber:innen verstehen, dass sie durch die Vereinbarung im Direktkredit-Vertrag als Nachrangdarlehen mit qualifiziertem Rangrücktritt das wirtschaftliche Risiko der Unternehmung in Höhe der Darlehenssumme sowie der Zinsen tragen. Dies bedeutet, dass im Falle von finanziellen Schwierigkeiten die Rückzahlung ihrer Darlehen erst nach anderen Gläubigern erfolgt, im schlimmsten Falle ist gar ein Totalverlust möglich. Deshalb möchten wir das Risiko auf viele einzelne Personen verteilen und suchen viele Menschen, die ihr Geld bei uns anlegen. Direktkredite bieten die Möglichkeit einer sinnvollen, sozialen und nachhaltigen Geldanlage.

**Wichtiger Hinweis**\
Die Rückzahlung des Kredits und die Zahlung der Zinsen kann nicht verlangt werden, solange die Kreditnehmerin dieses Kapital zur Erfüllung ihrer (nicht nachrangigen) fälligen Verbindlichkeiten benötigt, d.h. es handelt sich um ein nachrangiges Darlehen. Auch im Insolvenz- und Liquidationsfall tritt der/die Kreditgeber/in mit seiner/ihrer Rückzahlungsforderung im Rang hinter die Forderungen aller Gläubiger zurück.\
Der/die Kreditgeber/in kann seinen/ihren Anspruch auf Rückzahlung des Kredits und der Zinsen nicht geltend machen, wenn dies zur Überschuldung oder Zahlungsunfähigkeit der Kreditnehmerin führt. Die Rückzahlung des Kredits kann insofern nicht garantiert werden, d.h. es handelt sich nicht um einen unbedingten Rückzahlungsanspruch.

**Was wir Euch bieten können:**

## **Realistische Finanzplanung**

Unser Finanzierungsplan wurde in enger Zusammenarbeit mit Berater:Innen des Mietshäusersyndikats erarbeitet. Mit den Mieteinnahmen werden nun die Kosten für Kapitaldienst, also Zins und Tilgung der Kredite sowie die Hausbewirtschaftungskosten abgedeckt. Dabei werden zunächst die Bankkredite getilgt. Wenn Direktkreditgeber:Innen ihr Geld wieder selbst benötigen, werben wir neue Direktkredite an. Durch die gut planbaren Kündigungsfristen stellt dies erfahrungsgemäß kein Problem dar - circa 200 Projekte des Mietshäusersyndikats zeigen, dass es funktioniert. Bei Interesse legen wir unsere Finanzierungspläne gerne offen und erklären sie.

## **Solidarzusammenschluss**

Das Freiau99-Hausprojekt ist Teil des Mietshäuser Syndikats, unter dessen Dach seit über dreißig Jahren inzwischen circa 200 gut funktionierende und von vielen Menschen getragene Projekte existieren, die mit dem Solidarbeitrag die Entstehung neuer Projekte unterstützen. Die Projekte sind untereinander vernetzt und unterstützen sich gegenseitig. Zusätzlich können wir lokal auf das Know-How und die Erfahrung des Mietshäuser Syndikats zurückgreifen.

## **Lokale und transparente Geldanlage**

Ihr könnt jederzeit vor Ort sehen, wo Euer Geld steckt und was damit geschieht. In Form eines Newsletters bekommt ihr regelmäßig Informationen über die Entwicklung des Projekts. So bleibt die Verwendung Eurer Geldanlage transparent.
