---
title: "August 2025"
page-layout: full
date: 2025-08-14
---

Hallo liebe Leute,

viele von euch kennen wir, mit manchen teilen wir nun seit längerem schon einen mehr oder weniger regen Emailaustausch und sind so zumindest in Schriftform miteinander vertraut. Länger denken wir uns schon, wie gern wir eigentlich auch mal alle zusammenkommen, auf die tolle gemeinsame Zeit anstoßen und so die Gesichter hinter den Mails und Kapitalanlagen wiedersehen oder kennenlernen möchten.

Deswegen möchten wir mit dieser Mail gern mal vorfühlen, ob ihr da auch Lust drauf habt. Angedacht ist ein kleines Zusammenkommen zu Kaltgetränken und Snacks zur frühen abendlichen Stunde in unserem Garten um den September/ Oktober herum.

Gebt uns gern Rückmeldung, ob ihr Interesse daran habt und welcher Monat/Zeitraum euch taugen würde. Wir kommen danach konkreter wieder auf euch zurück.

Außerdem dachten wir, wir nutzen die Gunst dieser Mail auch, um mal hier mal wieder ein kleines Zwischenupdate von uns zu abzugeben.

Ansonsten bleiben wir den Vorurteilen einer jungen, fluktuierenden Wohnendenschaft treu und bekunden hier mal wieder Neuerung in der Wohnkonstellation. Mit Freude dürfen wir unseren neuen Mitbewohner und nun 10. Mitglied im Bunde begrüßen: unseren Kater Arschi (\* Der Name “Arschi” symbolisiert die neckend-liebevolle Beziehung die wir mit unserem 4-beinigen Freund pflegen und in der wir auf sein facettenreiches Wesen zwischen Kratzbürstigkeit und Kuscheligkeit Bezug nehmen). Zwar schon lange präsent, ist er nun offiziell adoptiert. Das mit den damit erworbenen Rechten wie einer vollgefüllten Futterschale auf jeder Etage und einer Katzenklappe (die aufgrund Arschis Größe eigentlich eine Hundeklappe ist) auch Pflichten und Verantwortungen in der Hausgemeinschaft einhergehen, ignoriert er zwar noch mit der eleganten Arroganz eines Katers, aber wir sind zuversichtlich.

Der Ignoranz Arschis um einen Ausgleich bemüht, ist der die Kreativität und Tüftelei unseres Mitbewohners Marius kein Halt geboten. Ganz mit dem Zahn der Zeit, verfügen wir nun über einen vollautomatisierten Kontoauszug-Emailversand. Danke Marius!

Ansonsten: wer es gar nicht abwarten kann, uns persönlich anzutreffen, muss gar nicht auf unsere anstehenden Zusammentreffen warten, sondern kann uns direkt life live und in Farbe jeden Mittwochnachmittag auf dem Vaubanmarkt antreffen. Denn so semi fluide wie unser Wohnumfeld ist auch die Direktkreditsituation eines Mietshäusersyndikats. In dem Konzept: „lieber von 1000 Freunden die Tacken als eine böse Bank im Nacken“ ist es normal, dass Freunde ihre Kredite zurücknehmen und wir immer mehr oder weniger intensiv nach Neuen suchen. So sind auch wir mal wieder auf dem Markt anzutreffen. Und auch hier nochmal ein kleiner Rundruf: wenn ihr Menschen kennt, die ein bisschen zu viel auf der hohen Kante haben, freuen wir uns selbstverständlich auch sehr über eine Unterstützung ohne den Umweg über den Markt! So gern wir ihn auch haben..

Also, genug von uns erstmal! Meldet euch gern bei uns wegen Rückmeldung zum Zusammenkommen, bei Durchreise und Unterkunftsnotwendigkeit oder Kontakt zu potentiellenpotenziellen Direktkredit-Unterstützenden, wir freuen uns immer, von euch zu hören!

Liebe Grüße, eure F99 \<3
